### ISSUE TITLE
Error in 'python setup.py install'

### ISSUE THREAD

**Issue by 1-w** [JosephIsaacTurner/easyreg_standalone#1]
Seems like pzproject.toml contains an erroneous "f"

Traceback (most recent call last):
  File "/.../wdir/easyreg_standalone/setup.py", line 4, in <module>
    setup(
  File "/.../.conda/envs/easyreg/lib/python3.9/site-packages/setuptools/__init__.py", line 104, in setup
    return distutils.core.setup(**attrs)
  File "/.../.conda/envs/easyreg/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 158, in setup
    dist.parse_config_files()
  File "/.../.conda/envs/easyreg/lib/python3.9/site-packages/setuptools/dist.py", line 631, in parse_config_files
    pyprojecttoml.apply_configuration(self, filename, ignore_option_errors)
  File "/.../.conda/envs/easyreg/lib/python3.9/site-packages/setuptools/config/pyprojecttoml.py", line 68, in apply_configuration
    config = read_configuration(filepath, True, ignore_option_errors, dist)
  File "/.../.conda/envs/easyreg/lib/python3.9/site-packages/setuptools/config/pyprojecttoml.py", line 104, in read_configuration
    asdict = load_file(filepath) or {}
  File "/.../.conda/envs/easyreg/lib/python3.9/site-packages/setuptools/config/pyprojecttoml.py", line 36, in load_file
    return tomllib.load(file)
  File "/.../.conda/envs/easyreg/lib/python3.9/site-packages/setuptools/_vendor/tomli/_parser.py", line 66, in load
    return loads(s, parse_float=parse_float)
  File "/.../.conda/envs/easyreg/lib/python3.9/site-packages/setuptools/_vendor/tomli/_parser.py", line 102, in loads
    pos = key_value_rule(src, pos, out, header, parse_float)
  File "/.../.conda/envs/easyreg/lib/python3.9/site-packages/setuptools/_vendor/tomli/_parser.py", line 326, in key_value_rule
    pos, key, value = parse_key_value_pair(src, pos, parse_float)
  File "/.../.conda/envs/easyreg/lib/python3.9/site-packages/setuptools/_vendor/tomli/_parser.py", line 366, in parse_key_value_pair
    raise suffixed_err(src, pos, "Expected '=' after a key in a key/value pair")
setuptools._vendor.tomli.TOMLDecodeError: Expected '=' after a key in a key/value pair (at line 15, column 2)

**Comment by JosephIsaacTurner** [comment]
Thanks! Fixed
